[package]
name = "raytracer"
version = "0.1.0"
authors = ["themeshpotato <daniel@glitchheart.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
